#!/usr/bin/env python3
"""Tests for the pure helpers in ``code/_sanes_to_nwb.py``.

``build_nwb`` itself still needs real audio, video, SLEAP and annotation
fixtures this repository does not have yet (see ``labs/sanes/README.md``), so
what is covered here is the file-discovery logic that runs before any of that
and decides which files a chunk contributes.

Test functions take their arguments positionally by pytest's injection rules,
so the repository's keyword-only and positional-only conventions do not apply
to them.

Run with::

    python3 -m pytest tests/ -q
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

TESTS = Path(__file__).resolve().parent
REPO_ROOT = TESTS.parents[2]
sys.path.insert(0, str(REPO_ROOT))

from labs.sanes.code import _sanes_to_nwb  # noqa: E402

pytestmark = pytest.mark.ai_generated


@pytest.mark.parametrize("filename", ["annotations.csv", "channel_0_4_annotations.csv"])
def test_find_annotations_file_accepts_either_naming(tmp_path, filename):
    """Both namings appear across the chunks of one real upload (000522)."""
    (tmp_path / filename).touch()

    annotations_path = _sanes_to_nwb.find_annotations_file(tmp_path)

    assert annotations_path == tmp_path / filename


def test_find_annotations_file_ignores_the_tracks_csv(tmp_path):
    """Every chunk also holds a SLEAP tracks .csv, which is not the annotations table."""
    (tmp_path / "center-session_135_video-4.tracks.csv").touch()
    (tmp_path / "channel_0_4_annotations.csv").touch()

    annotations_path = _sanes_to_nwb.find_annotations_file(tmp_path)

    assert annotations_path == tmp_path / "channel_0_4_annotations.csv"


@pytest.mark.parametrize(
    ("filenames", "expected_found"),
    [
        ((), 0),
        (("center-session_135_video-4.tracks.csv",), 0),
        (("annotations.csv", "channel_0_4_annotations.csv"), 2),
    ],
)
def test_find_annotations_file_requires_exactly_one(tmp_path, filenames, expected_found):
    for filename in filenames:
        (tmp_path / filename).touch()

    with pytest.raises(ValueError, match=f"found {expected_found}"):
        _sanes_to_nwb.find_annotations_file(tmp_path)


@pytest.fixture()
def chunk_videos(tmp_path):
    """Two chunk videos in an incoming tree, and the output NWB path beside them."""
    incoming = tmp_path / "incoming" / "experiment_135"
    vid_files = []
    for index in range(2):
        chunk = incoming / f"idx_{index}"
        chunk.mkdir(parents=True)
        video = chunk / f"center-session_135_video-{index}.mp4"
        video.write_bytes(b"\x00" * (index + 1))
        vid_files.append(video)

    out_nwb = tmp_path / "standardized" / "autogenerated" / "sub-Gerbil001" / "sub-Gerbil001_ses-experiment135.nwb"
    out_nwb.parent.mkdir(parents=True)
    return vid_files, out_nwb


def test_copy_chunk_videos_copies_next_to_the_nwb(chunk_videos):
    """external_file must resolve from the NWB alone, since the incoming tree
    is not mounted when dispatch uploads the standardized dandiset."""
    vid_files, out_nwb = chunk_videos

    external_file = _sanes_to_nwb.copy_chunk_videos(vid_files=vid_files, out_nwb=out_nwb)

    assert external_file == [
        "sub-Gerbil001_ses-experiment135_center-session_135_video-0.mp4",
        "sub-Gerbil001_ses-experiment135_center-session_135_video-1.mp4",
    ]
    for name, source in zip(external_file, vid_files):
        copied = out_nwb.parent / name
        assert copied.is_file()
        assert copied.read_bytes() == source.read_bytes()


def test_copy_chunk_videos_reuses_an_identical_copy(chunk_videos):
    """A reconversion must not recopy gigabytes that are already in place."""
    vid_files, out_nwb = chunk_videos
    external_file = _sanes_to_nwb.copy_chunk_videos(vid_files=vid_files, out_nwb=out_nwb)
    first_mtime = (out_nwb.parent / external_file[0]).stat().st_mtime_ns

    _sanes_to_nwb.copy_chunk_videos(vid_files=vid_files, out_nwb=out_nwb)

    assert (out_nwb.parent / external_file[0]).stat().st_mtime_ns == first_mtime


def test_copy_chunk_videos_replaces_a_differing_copy(chunk_videos):
    vid_files, out_nwb = chunk_videos
    external_file = _sanes_to_nwb.copy_chunk_videos(vid_files=vid_files, out_nwb=out_nwb)
    stale = out_nwb.parent / external_file[0]
    stale.write_bytes(b"\x01\x02\x03")

    _sanes_to_nwb.copy_chunk_videos(vid_files=vid_files, out_nwb=out_nwb)

    assert stale.read_bytes() == vid_files[0].read_bytes()
