#!/usr/bin/env python3
"""Tests for ``code/batch_convert.py``.

``_sanes_to_nwb.build_nwb`` needs real audio, video, SLEAP and annotation
fixtures this repo doesn't have yet (see ``labs/sanes/README.md``), so these
tests cover the batch driver's own logic -- discovery, identity, the
``autogenerated/`` output layout, and the skip/overwrite bookkeeping -- with
``build_nwb`` stubbed out rather than exercised for real. A real end-to-end
integration test belongs with the follow-up that takes ownership of the port.

Test functions take their arguments positionally by pytest's injection rules,
so the repository's keyword-only and positional-only conventions do not apply
to them.

Run with::

    python3 -m pytest tests/ -q
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

TESTS = Path(__file__).resolve().parent
REPO_ROOT = TESTS.parents[2]
sys.path.insert(0, str(REPO_ROOT))

from labs.sanes.code import batch_convert  # noqa: E402

pytestmark = pytest.mark.ai_generated

CONFIG = TESTS.parent / "code" / "config.yaml"
SUBJECT = "Gerbil001002003"


def make_session(root, name, /, *, chunks=("idx_0",)):
    session_dir = root / name
    for chunk in chunks:
        (session_dir / chunk).mkdir(parents=True)
    return session_dir


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("session-1", "session1"),
        ("2025-06-25", "20250625"),
        ("!!!", ""),
    ],
)
def test_sanitize_label(text, expected):
    label = batch_convert.sanitize_label(text)
    assert label == expected


def test_discover_sessions(tmp_path):
    raw_dir = tmp_path / "incoming" / "sourcedata" / "raw"
    make_session(raw_dir, "session-1", chunks=("idx_0", "idx_1"))
    make_session(raw_dir, "session-2")
    (raw_dir / "notes.txt").write_text("not a session")

    sessions, ignored = batch_convert.discover_sessions(tmp_path / "incoming")

    assert [session.name for session in sessions] == ["session-1", "session-2"]
    assert ignored == []


def test_discover_sessions_reports_folders_without_chunks(tmp_path):
    """A folder holding no idx_* chunks is reported, not silently dropped."""
    raw_dir = tmp_path / "incoming" / "sourcedata" / "raw"
    make_session(raw_dir, "session-1")
    (raw_dir / "previous-work").mkdir()

    sessions, ignored = batch_convert.discover_sessions(tmp_path / "incoming")

    assert [session.name for session in sessions] == ["session-1"]
    assert [folder.name for folder in ignored] == ["previous-work"]


def test_discover_sessions_missing_raw_dir(tmp_path):
    assert batch_convert.discover_sessions(tmp_path / "incoming") == ([], [])


def test_output_path_nests_under_autogenerated():
    path = batch_convert.output_path(standardized_dir=Path("out"), subject="Gerbil001", session="session1")

    assert path == Path("out/autogenerated/sub-Gerbil001/sub-Gerbil001_ses-session1.nwb")


@pytest.fixture()
def sample_incoming(tmp_path):
    incoming = tmp_path / "incoming"
    make_session(incoming / "sourcedata" / "raw", "session-1")
    return incoming


def fake_build_nwb(*, input_folder, out_nwb, cfg):
    Path(out_nwb).write_text(str(input_folder))


def test_convert_batch_end_to_end(sample_incoming, tmp_path, monkeypatch):
    monkeypatch.setattr(batch_convert, "build_nwb", fake_build_nwb)
    standardized = tmp_path / "standardized"

    exit_code = batch_convert.convert_batch(
        incoming_dir=sample_incoming, standardized_dir=standardized, config_path=CONFIG
    )
    assert exit_code == 0

    nwb = standardized / "autogenerated" / f"sub-{SUBJECT}" / f"sub-{SUBJECT}_ses-session1.nwb"
    assert nwb.is_file()

    # A rerun without --overwrite must leave the existing output untouched.
    first_mtime = nwb.stat().st_mtime_ns
    exit_code = batch_convert.convert_batch(
        incoming_dir=sample_incoming, standardized_dir=standardized, config_path=CONFIG
    )
    assert exit_code == 0
    assert nwb.stat().st_mtime_ns == first_mtime

    # With overwrite=True the session is reconverted.
    exit_code = batch_convert.convert_batch(
        incoming_dir=sample_incoming, standardized_dir=standardized, config_path=CONFIG, overwrite=True
    )
    assert exit_code == 0
    assert nwb.stat().st_mtime_ns > first_mtime


def test_convert_batch_continues_past_failures(sample_incoming, tmp_path, monkeypatch, capsys):
    make_session(sample_incoming / "sourcedata" / "raw", "session-2")

    def flaky_build_nwb(*, input_folder, out_nwb, cfg):
        if Path(input_folder).name == "session-1":
            raise ValueError("boom")
        fake_build_nwb(input_folder=input_folder, out_nwb=out_nwb, cfg=cfg)

    monkeypatch.setattr(batch_convert, "build_nwb", flaky_build_nwb)
    standardized = tmp_path / "standardized"

    exit_code = batch_convert.convert_batch(
        incoming_dir=sample_incoming, standardized_dir=standardized, config_path=CONFIG
    )
    assert exit_code == 1, "a failed session must be reflected in the exit code"

    good_output = standardized / "autogenerated" / f"sub-{SUBJECT}" / f"sub-{SUBJECT}_ses-session2.nwb"
    assert good_output.is_file(), "the failure of one session must not stop the others"

    captured = capsys.readouterr()
    assert "FAILED" in captured.err


def test_convert_batch_no_sessions(tmp_path, capsys):
    exit_code = batch_convert.convert_batch(
        incoming_dir=tmp_path / "empty", standardized_dir=tmp_path / "standardized", config_path=CONFIG
    )

    assert exit_code == 0
    assert "No session folders found" in capsys.readouterr().out
