#!/usr/bin/env python3
"""Integration test for ``code/_zhang_ferret_hyperscanning_to_nwb.py``.

Runs the batch driver over the committed mock recording
(``tests/example_raw/``, generated by ``tests/generate_fixtures.py``) with
the project's own ``code/config.yaml`` and session log, then compares the
structural summary of what it produced against the golden
``tests/expected_output/summary.json``. NWB writes HDF5, which is not
byte-stable across library versions, so the comparison is on read-back
contents rather than on golden bytes as in ``labs/kemere/``.

Run with::

    python3 -m pytest tests/ -q
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

TESTS = Path(__file__).resolve().parent
PROJECT = TESTS.parent
sys.path.insert(0, str(TESTS))
sys.path.insert(0, str(PROJECT / "code"))

import batch_convert  # noqa: E402
from nwb_summary import summarize_output_tree  # noqa: E402

pytestmark = pytest.mark.ai_generated

EXAMPLE_RAW = TESTS / "example_raw"
EXPECTED_SUMMARY = TESTS / "expected_output" / "summary.json"
CONFIG = PROJECT / "code" / "config.yaml"


@pytest.fixture(scope="module")
def converted_dir(tmp_path_factory):
    assert EXAMPLE_RAW.is_dir(), "run tests/generate_fixtures.py first"
    output_dir = tmp_path_factory.mktemp("standardized")
    exit_code = batch_convert.convert_batch(
        incoming_dir=EXAMPLE_RAW, standardized_dir=output_dir, config_path=CONFIG, max_workers=1
    )
    assert exit_code == 0
    return output_dir


def test_output_matches_golden_summary(converted_dir):
    produced = summarize_output_tree(converted_dir)
    expected = json.loads(EXPECTED_SUMMARY.read_text())
    assert produced == expected


def test_second_pass_skips_converted_recording(converted_dir, capsys):
    exit_code = batch_convert.convert_batch(
        incoming_dir=EXAMPLE_RAW, standardized_dir=converted_dir, config_path=CONFIG, max_workers=1
    )
    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Exists, skipping" in captured.out
    assert "Converted 0, skipped 1, failed 0 of 1" in captured.out


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
