#!/usr/bin/env python3
"""Batch driver for the Sanes session-to-NWB conversion.

Discovers every session folder under an incoming directory tree's
``sourcedata/raw/`` (a session being a folder that holds ``idx_*`` chunk
folders, see ``_sanes_to_nwb.py``) and runs ``_sanes_to_nwb.build_nwb`` on
each, writing the results into the standardized output tree::

    <output>/
      autogenerated/
        sub-<subject>/
          sub-<subject>_ses-<session>.nwb

Output is nested under ``autogenerated/`` because the standardized dandiset
already holds earlier, hand-made work at its root. Everything this pipeline
produces stays inside that one subdirectory, so the two never mix.

Subject and session identity: the subject label comes from ``config.yaml``'s
``subject.id`` (the animals in a Sanes recording are a group, and the notebook
this port comes from names them with one id), and each session folder's
sanitized name is the session label. Both are provisional, like the rest of
``config.yaml``.

Outputs that already exist are skipped unless ``--overwrite`` is given.
Dispatch (``dispatch/projects.json``) relies on the flag. It re-runs this
script whenever new sessions appear in the incoming dandiset, and appends
``--overwrite`` when the core conversion script has changed.

Sessions are converted one at a time, not in parallel: ``build_nwb`` reads
every channel of every ``idx_*`` chunk into memory and concatenates them
before writing, so running several sessions concurrently would multiply that
memory pressure rather than just speed things up.

A failed session does not stop the batch. The remaining sessions are still
converted and the exit code reports whether any failed.

Example CLI usage (from the repository root)
--------------------------------------------
python3 labs/sanes/code/batch_convert.py \\
    --input ember-incoming/000522 --output ember-standardized/000523 \\
    --config labs/sanes/code/config.yaml
"""

import argparse
import re
import sys
import traceback
from pathlib import Path

import tqdm

# _sanes_to_nwb.py sits next to this file in a directory that is not an
# importable package path, so put that directory on sys.path and import the
# sibling by name.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _sanes_to_nwb import build_nwb, load_cfg  # noqa: E402

OUTPUT_SUBDIRECTORY = "autogenerated"


def sanitize_label(text, /):
    """Reduce *text* to an alphanumeric label usable in sub-/ses- names."""
    label = re.sub(r"[^0-9A-Za-z]", "", text)
    return label


def discover_sessions(incoming_dir, /):
    """Every session folder under *incoming_dir*'s ``sourcedata/raw/``.

    A session folder is one holding at least one ``idx_*`` chunk folder.
    Anything else found there is returned separately so the caller can report
    it rather than silently skipping it.
    """
    raw_dir = incoming_dir / "sourcedata" / "raw"
    if not raw_dir.is_dir():
        return [], []
    sessions = []
    ignored = []
    for candidate in sorted(p for p in raw_dir.iterdir() if p.is_dir()):
        chunks = [p for p in candidate.iterdir() if p.is_dir() and p.name.startswith("idx_")]
        if chunks:
            sessions.append(candidate)
        else:
            ignored.append(candidate)
    return sessions, ignored


def output_path(*, standardized_dir, subject, session):
    directory = standardized_dir / OUTPUT_SUBDIRECTORY / f"sub-{subject}"
    path = directory / f"sub-{subject}_ses-{session}.nwb"
    return path


def convert_batch(*, incoming_dir, standardized_dir, config_path, overwrite=False):
    cfg = load_cfg(config_path)
    subject = sanitize_label(cfg["subject"]["id"]) or "unknown"
    sessions, ignored = discover_sessions(incoming_dir)
    for candidate in ignored:
        print(f"Ignoring (no idx_* chunk folders): {candidate}", flush=True)
    if not sessions:
        print(f"No session folders found under {incoming_dir / 'sourcedata' / 'raw'}")
        return 0

    skipped = 0
    pending = []
    for session_dir in sessions:
        session = sanitize_label(session_dir.name) or "unknown"
        out_nwb = output_path(standardized_dir=standardized_dir, subject=subject, session=session)
        if out_nwb.is_file() and not overwrite:
            print(f"Exists, skipping (use --overwrite): {out_nwb}", flush=True)
            skipped += 1
            continue
        pending.append((session_dir, session, out_nwb))

    converted = 0
    failed = []
    for session_dir, session, out_nwb in tqdm.tqdm(pending, desc="Converting sessions", unit="session"):
        out_nwb.parent.mkdir(parents=True, exist_ok=True)
        try:
            build_nwb(input_folder=session_dir, out_nwb=out_nwb, cfg=cfg)
        except Exception as error:
            traceback.print_exception(error)
            print(f"FAILED: {session_dir}: {error}", file=sys.stderr, flush=True)
            failed.append(session_dir)
            continue
        converted += 1
        tqdm.tqdm.write(f"Converted {session_dir} (subject {subject}, session {session}) -> {out_nwb}")

    print(f"Converted {converted}, skipped {skipped}, failed {len(failed)} of {len(sessions)} session(s)", flush=True)
    exit_code = 1 if failed else 0
    return exit_code


def parse_args():
    parser = argparse.ArgumentParser(description="Convert every Sanes session folder under a directory to NWB")
    parser.add_argument("--input", required=True, type=Path, help="Incoming directory holding sourcedata/raw/")
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help=f"Standardized output directory. NWB files are written under its {OUTPUT_SUBDIRECTORY}/ subdirectory",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(__file__).parent / "config.yaml",
        help="YAML config (default: config.yaml next to this script)",
    )
    parser.add_argument("--overwrite", action="store_true", help="Reconvert sessions whose output NWB already exists")
    arguments = parser.parse_args()
    return arguments


def main():
    args = parse_args()
    exit_code = convert_batch(
        incoming_dir=args.input,
        standardized_dir=args.output,
        config_path=args.config,
        overwrite=args.overwrite,
    )
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
