#!/usr/bin/env python3
"""Integration test for ``code/inman_to_nwb.py``.

Runs the actual conversion on the committed mock walk session
(``tests/example_raw/``, generated by ``tests/generate_fixtures.py``) with the
filled-in ``tests/config.yaml``, then reads the produced NWB file back and
asserts its structure and contents match the fixture. NWB writes HDF5, which
is not byte-stable across library versions, so the assertion is on read-back
contents rather than on golden bytes as in ``labs/kemere/``.

Run with::

    python3 -m pytest tests/ -q
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy
import pymatreader
import pynwb
import pytest
import yaml

TESTS = Path(__file__).resolve().parent
REPO = TESTS.parent
sys.path.insert(0, str(REPO / "code"))

import inman_to_nwb  # noqa: E402

pytestmark = pytest.mark.ai_generated

EXAMPLE_MAT = TESTS / "example_raw" / "RWNApp_RW3_Walk1_restructured.mat"
CONFIG = TESTS / "config.yaml"

SESSION_START = datetime(2024, 6, 1, 12, 0, 0, tzinfo=timezone.utc)
NTP_DELTA = 2208988800.0


def _expected_timestamps(ntp_values, /):
    relative_seconds = numpy.asarray(ntp_values, dtype=numpy.float64) - NTP_DELTA - SESSION_START.timestamp()
    return relative_seconds


@pytest.fixture(scope="module")
def mat_data():
    assert EXAMPLE_MAT.is_file(), "run tests/generate_fixtures.py first"
    data = pymatreader.read_mat(EXAMPLE_MAT)
    return data


@pytest.fixture(scope="module")
def cfg():
    config = yaml.safe_load(CONFIG.read_text())
    return config


@pytest.fixture(scope="module")
def nwbfile(tmp_path_factory, mat_data, cfg):
    out_nwb = tmp_path_factory.mktemp("converted") / "InmanWalk-S3-Walk1.nwb"
    inman_to_nwb.build_nwb(data=mat_data, subject_name="3", session=1, out_nwb=out_nwb, cfg=cfg)
    with pynwb.NWBHDF5IO(out_nwb, "r") as io:
        yield io.read()


def test_session_and_subject_metadata(nwbfile, cfg):
    assert nwbfile.identifier == "InmanWalk-Subject3-Walk1"
    assert nwbfile.session_description == cfg["session"]["description"]
    assert nwbfile.session_start_time == SESSION_START
    assert nwbfile.subject.subject_id == cfg["subject"]["id"]
    assert nwbfile.subject.species == cfg["subject"]["species"]
    assert nwbfile.subject.sex == cfg["subject"]["sex"]
    assert nwbfile.subject.age == cfg["subject"]["age"]


def test_devices_created(nwbfile, cfg):
    device_names = set(nwbfile.devices)
    expected_names = {
        cfg["device_eyetracker"]["name"],
        cfg["device_imu"]["name"],
        cfg["device_ieeg"]["name"],
    }
    assert device_names == expected_names


def test_ambient_light_acquisition(nwbfile, mat_data, cfg):
    series = nwbfile.acquisition["AmbientLight"]
    assert series.unit == cfg["timeseries"]["ambient_light"]["unit"]
    numpy.testing.assert_allclose(series.data[:], mat_data["d_amb"])
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data["ntp_amb"]), atol=1e-5)


@pytest.mark.parametrize(
    ("container_name", "series_name", "data_key", "ntp_key", "unit_key"),
    [
        ("KDE-SignificantBehCalc", "KernelDensityEstimation", "d_kde", "ntp_kde", "kde"),
        ("MovementVelocityBehavioral", "MovementVelocity", "d_xs", "ntp_xs", "movement_velocity"),
        ("GazeFixationBehavioral", "GazeFixation", "d_gaze_fix", "ntp_gaze", "gaze_fixation"),
    ],
)
def test_behavioral_time_series(nwbfile, mat_data, cfg, container_name, series_name, data_key, ntp_key, unit_key):
    series = nwbfile.processing["behavior"][container_name].time_series[series_name]
    assert series.unit == cfg["timeseries"][unit_key]["unit"]
    numpy.testing.assert_allclose(series.data[:], mat_data[data_key])
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data[ntp_key]), atol=1e-5)


def test_gaze_position(nwbfile, mat_data, cfg):
    series = nwbfile.processing["behavior"]["EyeTracking"].spatial_series["GazePosition"]
    expected_data = numpy.column_stack((mat_data["d_gaze_x"], mat_data["d_gaze_y"]))
    assert series.reference_frame == cfg["timeseries"]["gaze_position"]["reference_frame"]
    numpy.testing.assert_allclose(series.data[:], expected_data)
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data["ntp_gaze"]), atol=1e-5)


@pytest.mark.parametrize(
    ("series_name", "imu_fields"),
    [
        ("IMUGyro", ["gyroX", "gyroY", "gyroZ"]),
        ("IMUAccel", ["accelX", "accelY", "accelZ"]),
    ],
)
def test_imu_spatial_series(nwbfile, mat_data, series_name, imu_fields):
    series = nwbfile.processing["behavior"][series_name]
    expected_data = numpy.column_stack([mat_data["d_imu"][field] for field in imu_fields])
    numpy.testing.assert_allclose(series.data[:], expected_data)
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data["ntp_imu"]), atol=1e-5)


def test_imu_orientation(nwbfile, mat_data):
    series = nwbfile.processing["behavior"]["IMUCompassDirection"].spatial_series["IMUOrientation"]
    expected_data = numpy.column_stack((mat_data["d_imu"]["roll"], mat_data["d_imu"]["pitch"]))
    numpy.testing.assert_allclose(series.data[:], expected_data)
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data["ntp_imu"]), atol=1e-5)


def test_behavior_annotations_table(nwbfile, mat_data):
    table = nwbfile.processing["behavior"]["BehaviorAnnotations"].to_dataframe()
    events = mat_data["evnts_struct"]
    assert list(table["Annotation"]) == list(events["Description"])
    assert list(table["Event"]) == list(events["Event"])
    numpy.testing.assert_array_equal(table["PupilFrame"].to_numpy(), numpy.asarray(events["PupilFrame"], dtype=int))
    numpy.testing.assert_array_equal(table["GoProFrame"].to_numpy(), numpy.asarray(events["GoProFrame"], dtype=int))
    numpy.testing.assert_array_equal(table["NPSample"].to_numpy(), numpy.asarray(events["NPSample"], dtype=int))
    numpy.testing.assert_allclose(table["NTP"].to_numpy(), events["NTP"])
    numpy.testing.assert_allclose(table["NTPRelative"].to_numpy(), _expected_timestamps(events["NTP"]), atol=1e-5)


def test_ieeg_electrical_series(nwbfile, mat_data, cfg):
    series = nwbfile.processing["iEEG"]["LFP"].electrical_series["ElectricalSeries"]
    assert series.filtering == cfg["lfp"]["filtering"]
    numpy.testing.assert_allclose(series.data[:], mat_data["d_np"])
    numpy.testing.assert_allclose(series.timestamps[:], _expected_timestamps(mat_data["ntp_np"]), atol=1e-5)


def test_electrodes_table(nwbfile, cfg):
    electrodes = nwbfile.electrodes.to_dataframe()
    channelmap = cfg["channelmap"]
    assert len(electrodes) == len(channelmap)
    assert list(electrodes["label"]) == list(channelmap)
    numpy.testing.assert_allclose(electrodes["x"].to_numpy(), [channel["x"] for channel in channelmap.values()])
    assert set(electrodes["group_name"]) == {cfg["electrode_group1"]["name"]}


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
