#!/usr/bin/env python3
"""Integration test for ``code/_suthana_in_lab_to_nwb.py``.

Runs the actual conversion on the committed mock recording
(``tests/example_raw/``, generated by ``tests/generate_fixtures.py``) with
the filled-in ``tests/config.yaml``, then reads the produced NWB file back
and asserts its structure and contents match the fixture. NWB writes HDF5,
which is not byte-stable across library versions, so the assertion is on the
read-back contents rather than on golden bytes as in ``labs/kemere/``.

Test functions take their arguments positionally by pytest's injection
rules, so the repository's keyword-only and positional-only conventions do
not apply to them.

Run with::

    python3 -m pytest tests/ -q
"""

from __future__ import annotations

import sys
from pathlib import Path

import h5py
import numpy
import pynwb
import pynwb.testing.mock.file
import pytest
import yaml

TESTS = Path(__file__).resolve().parent
CODE = TESTS.parent / "code"
sys.path.insert(0, str(CODE))

import _suthana_in_lab_to_nwb  # noqa: E402

sys.path.insert(0, str(TESTS))

import generate_fixtures  # noqa: E402

pytestmark = pytest.mark.ai_generated

EXAMPLE_RAW = TESTS / "example_raw"
EXAMPLE_MAT = EXAMPLE_RAW / generate_fixtures.MAT_FILENAME
EXAMPLE_RUNTIMES = EXAMPLE_RAW / generate_fixtures.RUNTIMES_FILENAME
CONFIG = TESTS / "config.yaml"

SAMPLE_RATE = generate_fixtures.SAMPLE_RATE
SEGMENT_COUNT = generate_fixtures.SEGMENT_COUNT
IEEG_CHANNEL_COUNT = generate_fixtures.IEEG_CHANNEL_COUNT
SCALP_CHANNEL_COUNT = generate_fixtures.SCALP_CHANNEL_COUNT

# The two fixture segments are recorded half an hour apart.
SECOND_SEGMENT_START = 1800.0


@pytest.fixture(scope="module")
def cfg():
    config = yaml.safe_load(CONFIG.read_text())
    return config


@pytest.fixture(scope="module")
def raw_segments():
    """The fixture's own per-segment matrices, read straight from the .mat."""
    assert EXAMPLE_MAT.is_file(), "run tests/generate_fixtures.py first"
    segments = []
    with h5py.File(EXAMPLE_MAT, "r") as mat_file:
        recordings = mat_file["Trajectories"]["recordings"]
        for index in range(SEGMENT_COUNT):
            segments.append(
                {
                    "gaze": mat_file[recordings["gaze"][index][0]][()],
                    "head_rotation": mat_file[recordings["head_rotation"][index][0]]["data"][()],
                    "position": mat_file[recordings["position"][index][0]]["data"][()],
                    "ieeg": mat_file[recordings["iEEG"][index][0]]["data"][()],
                    "ieeg_mask": mat_file[recordings["iEEG"][index][0]]["ix_IED"][()],
                    "scalp": mat_file[recordings["scalp_EEG"][index][0]]["data"][()],
                    "scalp_mask": mat_file[recordings["scalp_EEG"][index][0]]["ix_art"][()],
                }
            )
    return segments


@pytest.fixture(scope="module")
def nwbfile(tmp_path_factory, cfg):
    out_nwb = tmp_path_factory.mktemp("converted") / "sub-S1_ses-inlab_behavior+ecephys.nwb"
    _suthana_in_lab_to_nwb.convert_subject(
        mat_path=EXAMPLE_MAT,
        runtimes_path=EXAMPLE_RUNTIMES,
        out_nwb=out_nwb,
        cfg=cfg,
    )
    with pynwb.NWBHDF5IO(out_nwb, "r") as io:
        yield io.read()


def test_session_metadata(nwbfile, cfg):
    assert nwbfile.identifier == "SuthanaInLab-S1"
    assert nwbfile.session_description == cfg["session"]["description"]
    assert nwbfile.lab == cfg["session"]["lab"]
    assert nwbfile.institution == cfg["session"]["institution"]
    assert list(nwbfile.experimenter) == cfg["session"]["experimenter"]
    assert list(nwbfile.keywords) == cfg["session"]["keywords"]


def test_subject_metadata_comes_from_the_config_entry(nwbfile, cfg):
    expected = cfg["subjects"][generate_fixtures.SUBJECT_ID]
    assert nwbfile.subject.subject_id == expected["paper_id"]
    assert nwbfile.subject.age == expected["age"]
    assert nwbfile.subject.sex == expected["sex"]
    assert nwbfile.subject.species == cfg["subject"]["species"]


def test_session_start_time_is_shifted_away_from_the_recorded_date(nwbfile):
    """De-identification moves the date, so the raw one must not survive."""
    recorded_date = generate_fixtures.SEGMENT_START_TIMES[0][:10]
    assert nwbfile.session_start_time.strftime("%Y-%m-%d") != recorded_date


def test_deidentification_offset_is_reproducible(cfg):
    """A re-run must not invent new timestamps (the original's unseeded RNG did)."""
    first = _suthana_in_lab_to_nwb.segment_start_times(runtimes_path=EXAMPLE_RUNTIMES, paper_id="S1", cfg=cfg)
    second = _suthana_in_lab_to_nwb.segment_start_times(runtimes_path=EXAMPLE_RUNTIMES, paper_id="S1", cfg=cfg)
    assert first == second


def test_deidentification_preserves_spacing_between_segments(cfg):
    shifted = _suthana_in_lab_to_nwb.segment_start_times(runtimes_path=EXAMPLE_RUNTIMES, paper_id="S1", cfg=cfg)
    assert (shifted[1] - shifted[0]).total_seconds() == SECOND_SEGMENT_START


def test_deidentification_can_be_disabled(cfg):
    unshifted_cfg = {**cfg, "deidentification": {"enabled": False}}
    unshifted = _suthana_in_lab_to_nwb.segment_start_times(
        runtimes_path=EXAMPLE_RUNTIMES, paper_id="S1", cfg=unshifted_cfg
    )
    assert unshifted[0].strftime("%Y-%m-%d %H:%M:%S") == generate_fixtures.SEGMENT_START_TIMES[0]


def test_devices_created(nwbfile, cfg):
    expected = {cfg["device_ieeg"]["name"], cfg["device_scalp_eeg"]["name"]}
    assert set(nwbfile.devices) == expected


def test_electrode_table_holds_both_arrays(nwbfile, cfg):
    assert len(nwbfile.electrodes) == IEEG_CHANNEL_COUNT + SCALP_CHANNEL_COUNT
    labels = list(nwbfile.electrodes["label"][:])
    assert labels[:IEEG_CHANNEL_COUNT] == [f"iEEG {index}" for index in range(IEEG_CHANNEL_COUNT)]
    assert labels[IEEG_CHANNEL_COUNT] == f"sEEG 0: {cfg['scalp_eeg_channels'][0]}"


def test_ieeg_electrode_locations_come_from_the_subject_entry(nwbfile, cfg):
    expected = cfg["subjects"][generate_fixtures.SUBJECT_ID]["ieeg_channels"]
    locations = list(nwbfile.electrodes["location"][:IEEG_CHANNEL_COUNT])
    assert locations == expected


@pytest.mark.parametrize("subject_id", ["R095", "R133"])
def test_empty_ieeg_channel_entries_get_a_placeholder_location(cfg, subject_id):
    """An empty ieeg_channels entry still occupies a row (see config.yaml),
    but pynwb rejects an empty location outright, so it must become some
    non-empty placeholder rather than reach add_electrode as-is."""
    ieeg_channels = cfg["subjects"][subject_id]["ieeg_channels"]
    assert "" in ieeg_channels, "fixture must exercise the empty-entry case"

    mock_nwbfile = pynwb.testing.mock.file.mock_NWBFile()
    _suthana_in_lab_to_nwb.add_electrodes(nwbfile=mock_nwbfile, cfg=cfg, ieeg_channels=ieeg_channels)

    locations = list(mock_nwbfile.electrodes["location"][:IEEG_CHANNEL_COUNT])
    assert locations == [channel or "none" for channel in ieeg_channels]


@pytest.mark.parametrize(
    ("module_name", "series_name", "expected_rows"),
    [
        ("iEEG", "Processed iEEG Segment 01", list(range(IEEG_CHANNEL_COUNT))),
        (
            "scalp EEG",
            "Processed scalp EEG Segment 01",
            list(range(IEEG_CHANNEL_COUNT, IEEG_CHANNEL_COUNT + SCALP_CHANNEL_COUNT)),
        ),
    ],
)
def test_electrical_series_reference_their_own_electrode_rows(nwbfile, module_name, series_name, expected_rows):
    """The scalp series must point past the iEEG rows, not overlap them."""
    series = nwbfile.processing[module_name][series_name]
    assert [int(row) for row in series.electrodes.data] == expected_rows


@pytest.mark.parametrize("segment", range(1, SEGMENT_COUNT + 1))
def test_every_segment_is_present_in_every_module(nwbfile, segment):
    behavior = nwbfile.processing["behavior"]
    assert f"Head Rotation Segment {segment:02d}" in behavior["HeadRotation_All"].spatial_series
    assert f"Gaze Position Segment {segment:02d}" in behavior["EyeTracking_All"].spatial_series
    assert f"Processed iEEG Segment {segment:02d}" in nwbfile.processing["iEEG"].data_interfaces
    assert f"Processed scalp EEG Segment {segment:02d}" in nwbfile.processing["scalp EEG"].data_interfaces


@pytest.mark.parametrize("part", ["Hip", "LeftLeg", "RightLeg", "Head"])
def test_position_centroids_are_split_by_body_part(nwbfile, raw_segments, part):
    rows = dict(_suthana_in_lab_to_nwb.POSITION_PARTS)[part]
    series = nwbfile.processing["behavior"][f"Pose_{part}_All"][f"{part} Centroid Segment 01"]
    expected = raw_segments[0]["position"][rows, :].T
    assert numpy.array_equal(series.data[:], expected) is True


def test_head_rotation_carries_the_column_labels_from_the_file(nwbfile):
    series = nwbfile.processing["behavior"]["HeadRotation_All"]["Head Rotation Segment 01"]
    assert series.description.endswith(", ".join(generate_fixtures.HEAD_ROTATION_LABELS))


def test_gaze_matches_the_fixture(nwbfile, raw_segments):
    series = nwbfile.processing["behavior"]["EyeTracking_All"]["Gaze Position Segment 01"]
    assert numpy.array_equal(series.data[:], raw_segments[0]["gaze"].T) is True


@pytest.mark.parametrize(
    ("module_name", "series_name", "raw_key"),
    [
        ("iEEG", "Processed iEEG Segment 01", "ieeg"),
        ("scalp EEG", "Processed scalp EEG Segment 01", "scalp"),
    ],
)
def test_electrical_series_data_matches_the_fixture(nwbfile, raw_segments, module_name, series_name, raw_key):
    series = nwbfile.processing[module_name][series_name]
    assert numpy.array_equal(series.data[:], raw_segments[0][raw_key].T) is True
    assert series.rate == SAMPLE_RATE
    assert series.conversion == pytest.approx(1e-6)


@pytest.mark.parametrize(
    ("module_name", "series_name", "raw_key"),
    [
        ("iEEG", "iEEG Artifact Series Segment 01", "ieeg_mask"),
        ("scalp EEG", "scalp EEG Artifact Series Segment 01", "scalp_mask"),
    ],
)
def test_artifact_masks_store_their_own_modality(nwbfile, raw_segments, module_name, series_name, raw_key):
    """The original wrote the iEEG mask into the scalp EEG series too."""
    series = nwbfile.processing[module_name][series_name]
    expected = raw_segments[0][raw_key].T.astype("uint8")
    assert numpy.array_equal(series.data[:], expected) is True


def test_segments_are_positioned_by_their_recorded_start_time(nwbfile):
    first = nwbfile.processing["iEEG"]["Processed iEEG Segment 01"]
    second = nwbfile.processing["iEEG"]["Processed iEEG Segment 02"]
    assert first.starting_time == 0.0
    assert second.starting_time == SECOND_SEGMENT_START


def test_beep_events_table(nwbfile):
    table = nwbfile.processing["behavior"]["beep_events"].to_dataframe()
    expected_objects = [obj for segment in generate_fixtures.BEEP_OBJECTS for obj in segment]
    expected_indices = [index for segment in generate_fixtures.BEEP_INDICES for index in segment]
    assert list(table["Object"]) == expected_objects
    assert [int(index) for index in table["Index"]] == expected_indices
    assert [int(segment) for segment in table["Segment"]] == [1, 1, 2]


def test_beep_event_times_are_session_relative(nwbfile):
    table = nwbfile.processing["behavior"]["beep_events"].to_dataframe()
    first_index = generate_fixtures.BEEP_INDICES[0][0]
    assert table["Time"][0] == pytest.approx((first_index - 1) / SAMPLE_RATE)
    last_index = generate_fixtures.BEEP_INDICES[1][0]
    assert table["Time"][2] == pytest.approx(SECOND_SEGMENT_START + (last_index - 1) / SAMPLE_RATE)


def test_button_events_table(nwbfile):
    table = nwbfile.processing["behavior"]["button_events"].to_dataframe()
    expected_responses = [value for segment in generate_fixtures.BUTTON_RESPONSES for value in segment]
    expected_indices = [index for segment in generate_fixtures.BUTTON_INDICES for index in segment]
    assert list(table["Response"]) == expected_responses
    assert [int(index) for index in table["Index"]] == expected_indices
    assert [int(value) for value in table["Correct"]] == [1, -1, 1]


def test_button_events_use_their_own_indices_not_the_beep_ones(nwbfile):
    """The original wrote the beep indices into the button table."""
    table = nwbfile.processing["behavior"]["button_events"].to_dataframe()
    beep_indices = [index for segment in generate_fixtures.BEEP_INDICES for index in segment]
    assert [int(index) for index in table["Index"]] != beep_indices


def test_event_tables_have_no_duplicated_rows(nwbfile):
    """The original concatenated each beep chunk into the table twice."""
    table = nwbfile.processing["behavior"]["beep_events"].to_dataframe()
    expected_row_count = sum(len(segment) for segment in generate_fixtures.BEEP_INDICES)
    assert len(table) == expected_row_count
