name: Tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: "labs/kemere/envs/.python-version"

      - name: Install test environment
        run: pip install "./labs/kemere/envs[test]"

      - name: Run the integration test
        run: python -m pytest labs/kemere/tests/ -q
